/**
 * Project Init Module — scaffolds a new OpenAdab project directory.
 */
import { readFile, readdir, copyFile } from 'node:fs/promises';
import { join } from 'node:path';

import YAML from 'yaml';

import { AdabError } from '../../utils/errors.js';
import { atomicWriteFile, ensureDir, fileExists } from '../../utils/fs.js';
import { resolveBuiltInSchemasDir, resolveCommandsDir } from '../../utils/resource-paths.js';
import {
  detectHost,
  CommandDefLoader,
  writeGeneratedFiles,
} from '../host-adapters/index.js';
import { AdapterFactory } from '../host-adapters/adapter-factory.js';

/**
 * Options passed to {@link ProjectInitializer.init}.
 */
export interface InitOptions {
  /** Schema name to set as active in the generated config. */
  schema?: string;
  /** Host adapter to generate (auto-detected if omitted). */
  host?: string;
}

/**
 * Scaffolds the `adab/` directory structure, default config, wiki templates,
 * built-in schemas, index files, and log for a fresh OpenAdab project.
 */
export class ProjectInitializer {
  private readonly targetDir: string;

  /**
   * @param targetDir Absolute path to the target project root.
   */
  constructor(targetDir: string) {
    this.targetDir = targetDir;
  }

  /**
   * Initialize a new OpenAdab project.
   *
   * Creates all required directories, default files, and built-in schema copies.
   * If `adab/` exists but `config.yaml` is missing (half-initialized state),
   * automatically recovers by creating the missing configuration.
   *
   * @param options Optional initialization overrides.
   * @throws {AdabError} If the project has already been fully initialized.
   */
  async init(options: InitOptions = {}): Promise<void> {
    const adabDir = join(this.targetDir, 'adab');
    const configPath = join(adabDir, 'config.yaml');

    if (await fileExists(adabDir)) {
      if (await fileExists(configPath)) {
        throw new AdabError(
          `Project already initialized: ${adabDir} exists. Use \`openadab update\` to refresh schemas and host adapters.`,
          'PROJECT_ALREADY_INITIALIZED'
        );
      }
      // Half-initialized state: adab/ exists but config.yaml is missing.
      // Automatically recover by creating missing files.
      await this.scaffoldDirectories(adabDir);
      await this.createDefaultWikiTemplates(adabDir);
      await this.createDefaultConfig(adabDir, options.schema ?? 'chapter-draft');
      await this.copyBuiltInSchemas(adabDir);
      await this.updateGitignore();
      await this.createLogMd(adabDir);
      await this.createEmptyIndexFiles(adabDir);
      await this.generateHostAdapters(options.host);
      return;
    }

    await this.scaffoldDirectories(adabDir);
    await this.createDefaultWikiTemplates(adabDir);
    await this.createDefaultConfig(adabDir, options.schema ?? 'chapter-draft');
    await this.copyBuiltInSchemas(adabDir);
    await this.updateGitignore();
    await this.createLogMd(adabDir);
    await this.createEmptyIndexFiles(adabDir);
    await this.generateHostAdapters(options.host);
  }

  private async scaffoldDirectories(adabDir: string): Promise<void> {
    const dirs = [
      join(adabDir, 'manuscript'),
      join(adabDir, 'manuscript', 'chapters'),
      join(adabDir, 'manuscript', 'scenes'),
      join(adabDir, 'wiki'),
      join(adabDir, 'wiki', 'characters'),
      join(adabDir, 'wiki', 'locations'),
      join(adabDir, 'wiki', 'factions'),
      join(adabDir, 'wiki', 'objects'),
      join(adabDir, 'wiki', 'timeline'),
      join(adabDir, 'wiki', 'threads'),
      join(adabDir, 'wiki', 'motifs'),
      join(adabDir, 'wiki', 'style'),
      join(adabDir, 'raw'),
      join(adabDir, 'raw', 'notes'),
      join(adabDir, 'raw', 'research'),
      join(adabDir, 'raw', 'imported-drafts'),
      join(adabDir, 'raw', 'references'),
      join(adabDir, 'changes'),
      join(adabDir, 'changes', 'archive'),
      join(adabDir, 'schemas'),
      join(adabDir, 'index'),
    ];
    for (const d of dirs) {
      await ensureDir(d);
    }
    // adab/index/ is gitignored — .gitkeep would be noise
    const gitkeepDirs = dirs.filter((d) => d !== join(adabDir, 'index'));
    for (const d of gitkeepDirs) {
      await atomicWriteFile(join(d, '.gitkeep'), '');
    }
  }

  private async createDefaultWikiTemplates(adabDir: string): Promise<void> {
    const indexMd = `---
type: index
created: ${new Date().toISOString()}
---

# Wiki Index

<!-- TOC will be regenerated by the wiki engine -->
`;
    const overviewMd = `---
type: overview
created: ${new Date().toISOString()}
---

# Overview

## Setting

## Characters

## Conflict

## Current State
`;
    const contradictionsMd = `---
type: contradictions
created: ${new Date().toISOString()}
---

# Contradictions

<!-- Contradiction entries are appended by the wiki-diff engine -->
`;
    await atomicWriteFile(join(adabDir, 'wiki', 'index.md'), indexMd);
    await atomicWriteFile(join(adabDir, 'wiki', 'overview.md'), overviewMd);
    await atomicWriteFile(join(adabDir, 'wiki', 'contradictions.md'), contradictionsMd);
  }

  private async createDefaultConfig(adabDir: string, schema: string): Promise<void> {
    const config = {
      schema,
      version: 1,
      project: {
        title: 'Untitled Novel',
        language: 'zh-CN',
        genre: 'fantasy',
        tense: 'past',
        pov: 'limited-third',
      },
      context: {
        maxTokens: 18000,
        alwaysInclude: [],
        tokenHeuristic: 'chars-per-token',
        excludePatterns: [],
      },
      rules: {},
      archive: {
        backupOnOverwrite: false,
      },
    };
    await atomicWriteFile(join(adabDir, 'config.yaml'), YAML.stringify(config, { indent: 2, lineWidth: 0 }));
  }

  private async copyBuiltInSchemas(adabDir: string): Promise<void> {
    const builtInDir = resolveBuiltInSchemasDir(import.meta.url);
    if (!(await fileExists(builtInDir))) {
      throw new AdabError(
        `Built-in schema source directory not found: ${builtInDir}`,
        'BUILT_IN_SCHEMAS_NOT_FOUND'
      );
    }
    const entries = await readdir(builtInDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) {continue;}
      const srcDir = join(builtInDir, entry.name);
      const destDir = join(adabDir, 'schemas', entry.name);
      await ensureDir(destDir);
      await this.copyDirContents(srcDir, destDir);
    }
  }

  private async copyDirContents(src: string, dest: string): Promise<void> {
    const entries = await readdir(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = join(src, entry.name);
      const destPath = join(dest, entry.name);
      if (entry.isDirectory()) {
        await ensureDir(destPath);
        await this.copyDirContents(srcPath, destPath);
      } else {
        await copyFile(srcPath, destPath);
      }
    }
  }

  private async updateGitignore(): Promise<void> {
    const gitignorePath = join(this.targetDir, '.gitignore');
    const lines = [
      'adab/index/*.json',
      'adab/index/.last-mention-indexed',
      'adab/index/.last-progression-indexed',
      'adab/log.md',
      'adab/wiki/index.md',
      'adab/wiki/overview.md',
      'adab/wiki/contradictions.md',
    ];
    let content = '';
    if (await fileExists(gitignorePath)) {
      content = await readFile(gitignorePath, 'utf-8');
    }
    for (const line of lines) {
      if (!content.split('\n').some((l) => {
        const trimmed = l.trim();
        // Skip commented lines when checking for duplicates
        return trimmed === line || (trimmed.startsWith('# ') && trimmed.slice(2) === line);
      })) {
        const prefix = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
        content += `${prefix}${line}\n`;
      }
    }
    await atomicWriteFile(gitignorePath, content);
  }

  private async createLogMd(adabDir: string): Promise<void> {
    const now = new Date().toISOString();
    const payload = JSON.stringify({ ts: now, op: 'init', change: null, result: 'success' });
    const content = `<!-- log-entry ${payload} -->\n- **${now}** \`init\` — success\n\n`;
    await atomicWriteFile(join(adabDir, 'log.md'), content);
  }

  private async createEmptyIndexFiles(adabDir: string): Promise<void> {
    const files = ['mentions.json', 'wikilinks.json', 'progressions.json', 'context-map.json'];
    for (const f of files) {
      await atomicWriteFile(join(adabDir, 'index', f), '{}');
    }
  }

  /**
   * Generate host-native adapter files for the detected (or hinted) host.
   *
   * Resolves the commands directory, loads command definitions, instantiates
   * the appropriate adapter, generates files, and writes them to the project.
   * Errors are caught and logged as warnings so that init does not fail.
   *
   * @param hostHint Optional host name to override auto-detection.
   */
  private async generateHostAdapters(hostHint?: string): Promise<void> {
    let host: string | null;
    try {
      host = hostHint ?? (await detectHost(this.targetDir));
    } catch (err) {
      console.warn('[ProjectInit] Host detection failed:', err instanceof Error ? err.message : String(err));
      host = null;
    }
    if (host === null) {
      host = 'generic';
    }

    const commandsDir = resolveCommandsDir(import.meta.url);
    if (!(await fileExists(commandsDir))) {
      return;
    }

    let defs;
    try {
      defs = await new CommandDefLoader(commandsDir).loadAll();
    } catch (err) {
      console.warn('[ProjectInit] Command definition loading failed:', err instanceof Error ? err.message : String(err));
      return;
    }
    if (defs.length === 0) {
      return;
    }

    let adapter;
    try {
      adapter = AdapterFactory.create(host);
    } catch (err) {
      console.warn('[ProjectInit] Adapter creation failed:', err instanceof Error ? err.message : String(err));
      return;
    }

    let files;
    try {
      files = adapter.generate(defs);
    } catch (err) {
      console.warn('[ProjectInit] Adapter file generation failed:', err instanceof Error ? err.message : String(err));
      return;
    }

    try {
      await writeGeneratedFiles(this.targetDir, files);
    } catch (err) {
      console.warn('[ProjectInit] Failed to write generated adapter files:', err instanceof Error ? err.message : String(err));
      // Best-effort: don't crash init just because adapter file generation failed.
    }
  }
}
